# Generated by Django 5.1.5 on 2025-02-05 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_address_customuser_age_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='want_collect',
        ),
    ]
