# Generated by Django 5.1.5 on 2025-02-05 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customuser_want_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitation_time', models.DateTimeField(auto_now_add=True, verbose_name='Hora da Solicitação')),
                ('collection_time', models.DateTimeField(null=True, verbose_name='Hora da Coleta')),
                ('status', models.CharField(choices=[('in_progress', 'Em Andamento'), ('completed', 'Concluída')], default='in_progress', max_length=50, verbose_name='Status da Solicitação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Motorista')),
                ('requester', models.ForeignKey(limit_choices_to={'driver': False}, on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Coleta',
                'verbose_name_plural': 'Solicitações de Coleta',
                'db_table': 'collection_requests',
            },
        ),
    ]
