# Generated by Django 5.1.5 on 2025-02-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_collectionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrequest',
            name='description',
        ),
        migrations.AlterField(
            model_name='collectionrequest',
            name='collection_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora da Coleta'),
        ),
    ]
