# Generated by Django 5.1.5 on 2025-02-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_collectionrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='neighborhood',
            field=models.CharField(max_length=255, null=True, verbose_name='Bairro'),
        ),
    ]
